export enum RoleName {
    ROLE_USER,
    ROLE_ADMIN,
    ROLE_CUSTOMER_ADMIN,
    ROLE_FRONTDESK,
    ROLE_NURSE_PRACTITIONER,
    ROLE_PRACTITIONER,
    ROLE_PATIENT,
    ROLE_FACILITY_ADMIN,
    ROLE_NURSE,
    ROLE_NON_MEDICAL_PRACTITIONER,
    ROLE_SUPER_ADMIN
}
